import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CarbonParticles } from '@/components/CarbonParticles';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useEmissions } from '@/hooks/useEmissions';
import { useSession } from '@/hooks/useSession';
import { FileBarChart, Download, Award, Loader2 } from 'lucide-react';
import { Helmet } from 'react-helmet-async';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

const Reports = () => {
  const { summary, emissions } = useEmissions();
  const { user, sessionId } = useSession();
  const [isGenerating, setIsGenerating] = useState(false);
  
  const formatNumber = (n: number) => n >= 1000 ? `${(n/1000).toFixed(2)}t` : `${n.toFixed(1)}kg`;
  
  const generatePDFReport = async () => {
    setIsGenerating(true);
    
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let yPos = 20;
      
      // Header
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('Carbon Emissions Report', pageWidth / 2, yPos, { align: 'center' });
      yPos += 15;
      
      // Subtitle
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      doc.text('Generated by Senseible', pageWidth / 2, yPos, { align: 'center' });
      yPos += 5;
      doc.text(new Date().toLocaleDateString('en-IN', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      }), pageWidth / 2, yPos, { align: 'center' });
      yPos += 20;
      
      // Divider
      doc.setDrawColor(200);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 15;
      
      // Summary Section
      doc.setTextColor(0);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Emissions Summary', margin, yPos);
      yPos += 12;
      
      // Scope boxes
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      
      const boxWidth = (pageWidth - margin * 2 - 20) / 3;
      const boxes = [
        { label: 'Scope 1 (Direct)', value: formatNumber(summary.scope1), color: [34, 139, 34] },
        { label: 'Scope 2 (Energy)', value: formatNumber(summary.scope2), color: [65, 105, 225] },
        { label: 'Scope 3 (Indirect)', value: formatNumber(summary.scope3), color: [255, 140, 0] }
      ];
      
      boxes.forEach((box, i) => {
        const x = margin + i * (boxWidth + 10);
        doc.setFillColor(245, 245, 245);
        doc.roundedRect(x, yPos, boxWidth, 35, 3, 3, 'F');
        
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(box.label, x + boxWidth / 2, yPos + 12, { align: 'center' });
        
        doc.setFontSize(16);
        doc.setTextColor(box.color[0], box.color[1], box.color[2]);
        doc.setFont('helvetica', 'bold');
        doc.text(box.value, x + boxWidth / 2, yPos + 26, { align: 'center' });
      });
      
      yPos += 50;
      
      // Total
      doc.setFillColor(34, 139, 34);
      doc.roundedRect(margin, yPos, pageWidth - margin * 2, 30, 3, 3, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.text('Total Carbon Footprint', margin + 15, yPos + 13);
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.text(formatNumber(summary.total), pageWidth - margin - 15, yPos + 20, { align: 'right' });
      
      yPos += 45;
      
      // Emissions breakdown
      if (emissions.length > 0) {
        doc.setTextColor(0);
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text('Emissions Breakdown', margin, yPos);
        yPos += 12;
        
        // Table header
        doc.setFillColor(240, 240, 240);
        doc.rect(margin, yPos, pageWidth - margin * 2, 10, 'F');
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60);
        doc.text('Category', margin + 5, yPos + 7);
        doc.text('Scope', margin + 60, yPos + 7);
        doc.text('CO₂ Emissions', pageWidth - margin - 5, yPos + 7, { align: 'right' });
        yPos += 12;
        
        // Table rows
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(0);
        emissions.slice(0, 10).forEach((emission, i) => {
          if (yPos > 260) {
            doc.addPage();
            yPos = 20;
          }
          
          if (i % 2 === 0) {
            doc.setFillColor(250, 250, 250);
            doc.rect(margin, yPos - 4, pageWidth - margin * 2, 10, 'F');
          }
          
          doc.text(emission.category.charAt(0).toUpperCase() + emission.category.slice(1), margin + 5, yPos + 3);
          doc.text(`Scope ${emission.scope}`, margin + 60, yPos + 3);
          doc.text(formatNumber(emission.co2_kg), pageWidth - margin - 5, yPos + 3, { align: 'right' });
          yPos += 10;
        });
      }
      
      yPos += 20;
      
      // Footer
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setDrawColor(200);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
      
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.text('This report was generated automatically by Senseible.', margin, yPos);
      yPos += 5;
      doc.text('For compliance purposes, please ensure data has been verified.', margin, yPos);
      yPos += 8;
      doc.text(`Report ID: ${crypto.randomUUID().slice(0, 8).toUpperCase()}`, margin, yPos);
      
      // Save the PDF
      doc.save(`carbon-report-${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('Report downloaded successfully');
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error('Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };
  
  const generateComplianceCertificate = async () => {
    setIsGenerating(true);
    
    try {
      const doc = new jsPDF({ orientation: 'landscape' });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      
      // Border
      doc.setDrawColor(34, 139, 34);
      doc.setLineWidth(3);
      doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
      doc.setLineWidth(0.5);
      doc.rect(15, 15, pageWidth - 30, pageHeight - 30);
      
      // Certificate title
      doc.setFontSize(32);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 139, 34);
      doc.text('CARBON COMPLIANCE CERTIFICATE', pageWidth / 2, 45, { align: 'center' });
      
      // Decorative line
      doc.setDrawColor(34, 139, 34);
      doc.setLineWidth(1);
      doc.line(60, 55, pageWidth - 60, 55);
      
      // Certificate text
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60);
      doc.text('This is to certify that', pageWidth / 2, 75, { align: 'center' });
      
      // Organization name
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      const orgName = user?.email?.split('@')[0] || 'Organization';
      doc.text(orgName.charAt(0).toUpperCase() + orgName.slice(1), pageWidth / 2, 92, { align: 'center' });
      
      // Certificate body
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60);
      doc.text('has successfully documented and verified their carbon emissions', pageWidth / 2, 110, { align: 'center' });
      doc.text('in accordance with environmental compliance standards.', pageWidth / 2, 120, { align: 'center' });
      
      // Emissions verified
      doc.setFillColor(245, 250, 245);
      doc.roundedRect(pageWidth / 2 - 60, 130, 120, 30, 5, 5, 'F');
      doc.setFontSize(11);
      doc.setTextColor(100);
      doc.text('Total Verified Emissions', pageWidth / 2, 142, { align: 'center' });
      doc.setFontSize(18);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 139, 34);
      doc.text(formatNumber(summary.total) + ' CO₂', pageWidth / 2, 155, { align: 'center' });
      
      // Date
      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(80);
      doc.text(`Issued on: ${new Date().toLocaleDateString('en-IN', { 
        day: 'numeric', 
        month: 'long', 
        year: 'numeric' 
      })}`, pageWidth / 2, 175, { align: 'center' });
      
      // Certificate ID
      const certId = `CERT-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0, 4).toUpperCase()}`;
      doc.setFontSize(9);
      doc.setTextColor(120);
      doc.text(`Certificate ID: ${certId}`, pageWidth / 2, pageHeight - 25, { align: 'center' });
      
      // Powered by
      doc.text('Powered by Senseible Carbon Platform', pageWidth / 2, pageHeight - 18, { align: 'center' });
      
      // Save
      doc.save(`compliance-certificate-${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('Certificate downloaded successfully');
    } catch (error) {
      console.error('Certificate generation error:', error);
      toast.error('Failed to generate certificate');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="relative min-h-screen w-full bg-background">
      <Helmet><title>Reports — Senseible</title></Helmet>
      <CarbonParticles />
      
      <header className="relative z-10 border-b border-border/50 bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="text-xl font-semibold text-foreground">senseible</Link>
          <nav className="flex items-center gap-6 text-sm text-muted-foreground">
            <Link to="/dashboard" className="hover:text-foreground transition-colors">Dashboard</Link>
            <Link to="/history" className="hover:text-foreground transition-colors">History</Link>
            <Link to="/reports" className="text-foreground font-medium">Reports</Link>
          </nav>
        </div>
      </header>
      
      <main className="relative z-10 container mx-auto px-4 py-8 max-w-2xl">
        <h1 className="text-2xl font-semibold mb-2">Carbon Reports</h1>
        <p className="text-muted-foreground mb-8">Generate compliance reports and certificates for stakeholders</p>
        
        {summary.total > 0 ? (
          <div className="space-y-6">
            {/* Emissions Report Card */}
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-4 mb-6">
                  <div className="p-3 rounded-lg bg-success/10">
                    <FileBarChart className="h-6 w-6 text-success" />
                  </div>
                  <div>
                    <h2 className="font-semibold">Emissions Summary Report</h2>
                    <p className="text-sm text-muted-foreground">Detailed breakdown of your carbon footprint</p>
                  </div>
                </div>
                
                <div className="grid grid-cols-3 gap-4 mb-6">
                  <div className="p-3 rounded-lg bg-secondary/50 text-center">
                    <div className="text-lg font-bold text-foreground">{formatNumber(summary.scope1)}</div>
                    <div className="text-xs text-muted-foreground">Scope 1</div>
                  </div>
                  <div className="p-3 rounded-lg bg-secondary/50 text-center">
                    <div className="text-lg font-bold text-foreground">{formatNumber(summary.scope2)}</div>
                    <div className="text-xs text-muted-foreground">Scope 2</div>
                  </div>
                  <div className="p-3 rounded-lg bg-secondary/50 text-center">
                    <div className="text-lg font-bold text-foreground">{formatNumber(summary.scope3)}</div>
                    <div className="text-xs text-muted-foreground">Scope 3</div>
                  </div>
                </div>
                
                <Button 
                  className="w-full" 
                  onClick={generatePDFReport}
                  disabled={isGenerating}
                >
                  {isGenerating ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Download className="h-4 w-4 mr-2" />
                  )}
                  Download PDF Report
                </Button>
              </CardContent>
            </Card>
            
            {/* Compliance Certificate Card */}
            <Card>
              <CardContent className="p-6">
                <div className="flex items-center gap-4 mb-6">
                  <div className="p-3 rounded-lg bg-primary/10">
                    <Award className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <h2 className="font-semibold">Compliance Certificate</h2>
                    <p className="text-sm text-muted-foreground">Official carbon compliance documentation</p>
                  </div>
                </div>
                
                <p className="text-sm text-muted-foreground mb-4">
                  Generate a compliance certificate to share with banks, investors, or regulatory bodies.
                  This certificate confirms your verified carbon emissions data.
                </p>
                
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={generateComplianceCertificate}
                  disabled={isGenerating}
                >
                  {isGenerating ? (
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  ) : (
                    <Award className="h-4 w-4 mr-2" />
                  )}
                  Download Certificate
                </Button>
              </CardContent>
            </Card>
          </div>
        ) : (
          <Card>
            <CardContent className="py-12 text-center">
              <FileBarChart className="h-12 w-12 text-muted-foreground/50 mx-auto mb-3" />
              <p className="text-muted-foreground mb-4">No emissions data to report</p>
              <Button variant="outline" asChild>
                <Link to="/">Upload Invoice</Link>
              </Button>
            </CardContent>
          </Card>
        )}
      </main>
    </div>
  );
};

export default Reports;
